### ISSUE TITLE
Better output for sssom validate

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#199]
```
sssom validate mappings/mgi_alzheimer_mp_hpo.sssom.tsv
```

We should not print stack traces _ever_ unless unhandled exception. This is the output of the above.

```
/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
--- Logging error ---
Traceback (most recent call last):
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/sssom/io.py", line 80, in validate_file
    read_sssom_table(file_path=input_path)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/sssom/parsers.py", line 58, in read_sssom_table
    sssom_metadata = _read_metadata_from_table(file_path)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/sssom/parsers.py", line 593, in _read_metadata_from_table
    meta = yaml.safe_load(yamlstr)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 15, column 394:
     ... fel (orcid:0000-0003-2307-1226).									
```

This is the file:

```
#mapping_set_id: MGI_Alzheimer_MP_HPO
#mapping_set_title: MP to HPO mappings for Alzheimer disease related phenotypes
#creator_id: orcid:0000-0003-4606-0597|orcid:0000-0003-2307-1226|ror:021sy4w91|wikidata:Q1951035
#license: https://creativecommons.org/licenses/by/4.0/
#mapping_set_group: MGI_MP_HPO
#object_source: http://purl.obolibrary.org/hpo.owl
#subject_source: http://purl.obolibrary.org/mp.owl
#curie_map:
#  HP: http://purl.obolibrary.org/obo/HP_
#  MP: http://purl.obolibrary.org/obo/MP_
#  skos: http://www.w3.org/2004/02/skos/core/
#  orcid: https://orcid.org/
#  ror: https://ror.org/
#  wikidata: https://www.wikidata.org/wiki/
#mapping_set_description: Symptoms for Alzheimer's disease were collected from the published literature and OMIM.org. Phenotype terms in MP and HPO corresponding to these phenotypes were identified and used to define the set of terms for these mappings. This work was primarily done as part of a summer research  project for Mouse Genome Informatics by Sarah Stofel (orcid:0000-0003-2307-1226).									
subject_id	subject_label	predicate_id	object_id	object_label	match_type	confidence	author_id	mapping_date	comment
MP:0003329	amyloid beta deposits	skos:closeMatch	HP:0100256	Senile plaques	HumanCurated	0.9	orcid:0000-0003-2307-1226	2021-07-29	
```

**Comment by matentzn** [comment]
In general error messages for CLI users should IMO never show a stack trace.
