### ISSUE TITLE
sssom-py (and linkml?) should not have network dependencies

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#247]
When trying to run `sssom` w/o an internet connection, I get this error:

```
Traceback (most recent call last):
  File "/Users/matentzn/opt/anaconda3/bin/sssom", line 5, in <module>
    from sssom.cli import main
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/sssom/__init__.py", line 3, in <module>
    from .sssom_datamodel import slots  # noqa:401
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/sssom/sssom_datamodel.py", line 16, in <module>
    from linkml_runtime.linkml_model.meta import (
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/linkml_runtime/__init__.py", line 2, in <module>
    from linkml_runtime.utils.schemaview import SchemaView
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/linkml_runtime/utils/schemaview.py", line 9, in <module>
    from linkml_runtime.utils.namespaces import Namespaces
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/linkml_runtime/utils/namespaces.py", line 4, in <module>
    from prefixcommons import curie_util
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/prefixcommons/__init__.py", line 4, in <module>
    from .curie_util import expand_uri, contract_uri, NoPrefix
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/prefixcommons/curie_util.py", line 79, in <module>
    default_curie_maps = [read_biocontext('monarch_context'),read_biocontext('obo_context')]
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/prefixcommons/curie_util.py", line 75, in read_biocontext
    return read_remote_jsonld_context("https://raw.githubusercontent.com/prefixcommons/biocontext/master/registry/"+name+".jsonld")
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/prefixcommons/curie_util.py", line 56, in read_remote_jsonld_context
    with closing(requests.get(url, stream=False)) as resp:
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
```

@hrshdhgd can you make a ticket to whoever is at fault for this? Is this linkml runtime?

**Comment by hrshdhgd** [comment]
My guess for the cause of the error is:
```
File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/prefixcommons/curie_util.py", line 75, in read_biocontext
    return read_remote_jsonld_context("https://raw.githubusercontent.com/prefixcommons/biocontext/master/registry/"+name+".jsonld")
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/prefixcommons/curie_util.py", line 56, in read_remote_jsonld_context
```
It would be `prefixcommons`, I think.

**Comment by matentzn** [comment]
Which lib is making the call to prefix commons?

**Comment by hrshdhgd** [comment]
`prefixcommons` lib See: https://github.com/prefixcommons/prefixcommons-py/blob/677e4eda10d9ac99439cfdd9329f28058887ca78/prefixcommons/curie_util.py#L75

**Comment by cmungall** [comment]
There’s an issue on the linkml tracker for this altready. Can you comment
on it and we will prioritize it?

**Comment by matentzn** [comment]
Yes please, can you do it @hrshdhgd and link this issue here?

**Comment by hrshdhgd** [comment]
Done: https://github.com/linkml/linkml/issues/604#issuecomment-1121139263

**Comment by hrshdhgd** [comment]
Half addressed and the other half that remains:https://github.com/linkml/linkml/issues/866

**Comment by matentzn** [comment]
Error is fixed.
