### ISSUE TITLE
`subject_id` present, but `ValueError: subject_id must be supplied`

### ISSUE THREAD

**Issue by joeflack4** [mapping-commons/sssom-py#410]
## Overview
I am doing a face-check on the CLI using `tests/data/basic.tsv`, which is successfully used in several tests. However it is failing when using at least 1 CLI command.

## Error
Command: `poetry run sssom convert ~/Desktop/basic.tsv --output-format fhir --output ~/Desktop/basic.json`
Error: `ValueError: subject_id must be supplied`

<details><summary>Logs</summary>
<p>

```
poetry run sssom convert ~/Desktop/basic.tsv --output-format fhir --output ~/Desktop/basic.json; beep
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/joeflack4/projects/sssom-py/.tox/py/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/joeflack4/projects/sssom-py/.tox/py/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/joeflack4/projects/sssom-py/.tox/py/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/joeflack4/projects/sssom-py/.tox/py/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/joeflack4/projects/sssom-py/.tox/py/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/joeflack4/projects/sssom-py/src/sssom/cli.py", line 160, in convert
    convert_file(input_path=input, output=output, output_format=output_format)
  File "/Users/joeflack4/projects/sssom-py/src/sssom/io.py", line 54, in convert_file
    doc = parse_sssom_table(input_path)
  File "/Users/joeflack4/projects/sssom-py/src/sssom/parsers.py", line 290, in parse_sssom_table
    msdf = from_sssom_dataframe(df, prefix_map=meta_all.prefix_map, meta=meta_all.metadata)
  File "/Users/joeflack4/projects/sssom-py/src/sssom/parsers.py", line 485, in from_sssom_dataframe
    mlist.append(_prepare_mapping(Mapping(**mdict)))
  File "<string>", line 47, in __init__
  File "/Users/joeflack4/projects/sssom-py/.tox/py/lib/python3.10/site-packages/sssom_schema/datamodel/sssom_schema.py", line 263, in __post_init__
    self.MissingRequiredField("subject_id")
  File "/Users/joeflack4/projects/sssom-py/.tox/py/lib/python3.10/site-packages/linkml_runtime/utils/yamlutils.py", line 273, in MissingRequiredField
    raise ValueError(f"{field_name} must be supplied")
ValueError: subject_id must be supplied
```

</p>
</details> 

## Investigation
1. There is indeed a `subject_id` column in the `basic.tsv` (attached)
2. I also did a test with `example.sssom.tsv` and it converted just fine (attached)
3. Looking at the log, the source of the problem seems to be in `sssom-schema`. Is that from a separate repository? Where is it?

## Attachments
- [basic.tsv.zip](https://github.com/mapping-commons/sssom-py/files/12508759/basic.tsv.zip)
- [example.sssom.tsv.zip](https://github.com/mapping-commons/sssom-py/files/12508761/example.sssom.tsv.zip)

**Comment by joeflack4** [comment]
Hey @hrshdhgd, thanks for this help.

Firstly, I ran your command and it worked for me too. I didn't try running `sssom` before because I figured that it wouldn't work. I thought maybe these binaries didn't exist until a package is built / pip installed (but I guess that happens during the `tox` setup).

Secondly, interestingly enough, my original `poetry run` command that was failing before is now not failing. No idea why. I can't replicate now, so I'll close this issue.

As for the virtual environment location, I'm not really sure what is wrong / should be right with this setup. It's been about a year since I worked on `sssom-py`, and the last time, I remember that we were all using `tox` to do things like install and run tests. I am not using poetry directly to install anything. I just was not sure how to run the CLI (didn't know it was as easy as just using the normal `sssom` command), so I looked at the `pyproject.toml` and saw the poetry command, and tried that. That being said, I have had some weirdness with `tox` before. Again it's been about a year, but I remember something strange happening before, like every time I was running `tox` to do tests, it would do a reinstall of things, oscillating between two directories, `.tox/py` and `.tox/mypy`. I think Nico said he'd heard of something like that before. If that happens again, or if my setup does something again that seems to be hampering to progress, I'll reach out for help.
