### ISSUE TITLE
sssom invert chokes on `UnboundLocalError`

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom-py#493]
Eventually we will deprecated sssom invert, but for now we need it to work:

```
sssom invert mondo_exactmatch_omim.sssom.tsv -o test.sssom.tsv
```

results in:

```
/Users/matentzn/.pyenv/versions/3.11.7/lib/python3.11/site-packages/sssom/util.py:156: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("", np.nan, inplace=True)
Traceback (most recent call last):
  File "/Users/matentzn/.pyenv/versions/3.11.7/bin/sssom", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/matentzn/.pyenv/versions/3.11.7/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matentzn/.pyenv/versions/3.11.7/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/matentzn/.pyenv/versions/3.11.7/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matentzn/.pyenv/versions/3.11.7/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matentzn/.pyenv/versions/3.11.7/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matentzn/.pyenv/versions/3.11.7/lib/python3.11/site-packages/sssom/cli.py", line 758, in invert
    inverse_dictionary["inverse_predicate_map"],
    ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'inverse_dictionary' where it is not associated with a value
```

**Comment by hrshdhgd** [comment]
What does `inverse-predicates.yaml` look like?

**Comment by hrshdhgd** [comment]
ran this and it works for me just fine. Your PR needed a variable name change but it doesn't make a difference.

**Comment by matentzn** [comment]
Thank you! Fixed by #503
